version: "3.9"

services:
  api:
    build: .
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgresql+psycopg://doadmin:${DB_PASSWORD}@pgbouncer:6432/${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer
    restart: unless-stopped

  celery_worker:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://doadmin:${DB_PASSWORD}@pgbouncer:6432/${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    command: celery -A app.workers.celery_app worker --loglevel=info
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer
    restart: unless-stopped

  celery_beat:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://doadmin:${DB_PASSWORD}@pgbouncer:6432/${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    command: celery -A app.workers.celery_app beat --loglevel=info
    depends_on:
      - redis
      - rabbitmq
      - pgbouncer
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0
    ports:
      - "6432:5432"  # Expose PgBouncer to other containers
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      RESERVE_POOL_SIZE: 0
      ADMIN_USERS: ${DB_USER}
    restart: unless-stopped
