"""make expa_person_id pk for expa_lead_status_snapshot

Revision ID: 9343f1b7e665
Revises: 238c5de6f01e
Create Date: 2026-01-14 18:01:21.432225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9343f1b7e665'
down_revision: Union[str, Sequence[str], None] = '238c5de6f01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
          IF EXISTS (
            SELECT expa_person_id
            FROM expa_lead_status_snapshot
            GROUP BY expa_person_id
            HAVING COUNT(*) > 1
          ) THEN
            RAISE EXCEPTION 'Duplicate expa_person_id values exist in expa_lead_status_snapshot';
          END IF;
        END $$;
    """)

    # Drop old PK (default name usually: expa_lead_status_snapshot_pkey)
    op.execute('ALTER TABLE expa_lead_status_snapshot DROP CONSTRAINT IF EXISTS expa_lead_status_snapshot_pkey;')

    # Drop unique constraint if it exists (since PK will enforce uniqueness)
    # Name is unknown (could be autogenerated). Drop by scanning is harder; simplest: try common name.
    op.execute('ALTER TABLE expa_lead_status_snapshot DROP CONSTRAINT IF EXISTS uq_expa_lead_status_snapshot_expa_person_id;')

    # Drop old surrogate id column
    op.drop_column("expa_lead_status_snapshot", "id")

    # Create new PK on expa_person_id
    op.create_primary_key(
        "expa_lead_status_snapshot_pkey",
        "expa_lead_status_snapshot",
        ["expa_person_id"],
    )


def downgrade() -> None:
    op.execute('ALTER TABLE expa_lead_status_snapshot DROP CONSTRAINT IF EXISTS expa_lead_status_snapshot_pkey;')

    op.add_column(
        "expa_lead_status_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.create_primary_key(
        "expa_lead_status_snapshot_pkey",
        "expa_lead_status_snapshot",
        ["id"],
    )
    op.create_unique_constraint(
        "uq_expa_lead_status_snapshot_expa_person_id",
        "expa_lead_status_snapshot",
        ["expa_person_id"],
    )
